# Generated by Django 4.1 on 2022-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_image',
            field=models.TextField(null=True),
        ),
    ]
