# Generated by Django 4.1 on 2022-08-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_rename_date_posts_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='related_links',
            field=models.TextField(null=True),
        ),
    ]
