# Generated by Django 4.1 on 2022-08-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
    ]
