# Generated by Django 4.1 on 2022-08-24 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
