# Generated by Django 4.1 on 2022-08-27 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_polls_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='polls',
            name='option3',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='option4',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='option5',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='votes3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='votes4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='votes5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polls',
            name='option1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='polls',
            name='option2',
            field=models.CharField(max_length=40),
        ),
    ]
