# Generated by Django 4.1 on 2022-08-29 03:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_alter_events_user_alter_polls_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='interested_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), null=True, size=None),
        ),
    ]
