# Generated by Django 4.1 on 2022-08-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_rename_user_posts_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user_username',
            new_name='user',
        ),
    ]
