# Generated by Django 4.1 on 2022-08-25 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_rename_user_username_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
